destinationsintime/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.urls import path, reverse_lazy
from django.views.generic.base import RedirectView


urlpatterns = [
    #------ Home Page (eras/)-------------------------------------------
    path('', views.home, name='home'),

    # ------Itineraries (/itins/)----------------------------------------  
    path('itins/', views.itins_index, name='itins_index'),
    path('itins/<int:itin_id>/', views.itins_detail, name='itins_detail'),
    path('itins/create/', views.ItinCreate.as_view(), name='itins_create'),
    path('itins/<int:pk>/update/', views.ItinUpdate.as_view(), name='itins_update'),
    path('itins/<int:pk>/delete/', views.ItinDelete.as_view(), name='itins_delete'),

    # ------Destinations (/dests/)------------------------------------------
    # index page for destinations (aka detail page for an era)
    path('eras/<int:era_id>/', views.destinations_index, name='dest_index'),
    # details page for destination
    path('eras/<int:era_id>/destination/<int:dest_id>', views.destinations_detail, name="dest_detail"),

    # ------Stops (/itins/)------------------------------------------------  
    path('eras/<int:era_id>/destination/<int:dest_id>/addstop/', views.add_stop, name='add_stop'),
    

     # ------Delete and Edit Stops (/itins/)-----------------------------  
    path('itins/<int:itinerary_id>/edit/<int:stop_id>/', views.edit_stop, name='edit_stop'),
    path('itins/<int:itinerary_id>/delete/<int:stop_id>/', views.delete_stop, name='delete_stop'),

    #--------- Path to head directly to the admin site-------------
    path('', RedirectView.as_view(url=reverse_lazy('admin:index'))),

    #----------- User sign up (/accounts/)---------------------------------
    path('accounts/signup/', views.signup, name='signup')

    

]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User
# user model is built in within django, so needs to be imported correctly

# Destination model
class Destination(models.Model):
    dest_name = models.CharField("Name",max_length=150)
    dest_description = models.TextField("Description",max_length=3000)
    dest_address = models.CharField("Address",max_length=300)
    # latitude and longitud can be negative and positive numbers with decimals
    dest_latitude = models.DecimalField("Latitude", max_digits=19, decimal_places=10)
    dest_longitude = models.DecimalField("Longitude", max_digits=19, decimal_places=10)
    # please don't display this on the rendering page, that info will be for maps API
    dest_country = models.CharField("Country",max_length=100)
    price_range = models.CharField("Price Range", max_length=100)

    def __str__(self):
        return self.dest_name

    def get_absolute_url(self):
        return reverse('dest_detail', kwargs={'pk': self.id})
    

# Era model
class Era(models.Model):
    era_name = models.CharField("Name", max_length=250)
    era_period = models.CharField("Period", max_length=200)
    era_description = models.TextField("Description", max_length=2000)
    # M:M with Era
    destinations = models.ManyToManyField(Destination)

    def __str__(self):
        return self.era_name


#  Itinerary model 
class Itinerary(models.Model):
    init_name = models.CharField("Name", max_length=100)
    itin_description = models.TextField("Description", max_length=1000)
    init_travel_date = models.DateField("Start Date")
    end_travel_date = models.DateField("End Date")
    user_budget = models.IntegerField("Budget")
# user model built within django
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"Journey from {self.init_travel_date} to {self.end_travel_date}"

    def get_absolute_url(self):
        return reverse('itins_detail', kwargs={'itin_id': self.id})
    

# Stop model
class Stop(models.Model):
    dest_name = models.CharField("Name", max_length=150)
    dest_description = models.CharField("Description", max_length=3000)
    init_date_at_dest = models.DateTimeField("Start")
    end_date_at_dest = models.DateTimeField("End")
    comments = models.TextField("Comments", max_length=3000)
# 1:M with destination
    destination = models.ForeignKey(Destination, on_delete=models.CASCADE, related_name='stop_destin')
# 1:M with itinerary
    itinerary = models.ForeignKey(Itinerary, on_delete=models.CASCADE, related_name='Itinerary_plan')

    def __str__(self):
        return f"{self.dest_name} from {self.init_date_at_dest} to {self.end_date_at_dest}"

    def get_absolute_url(self):
        return reverse('destinations_detail', args=[str(self.id)])
    
    class Meta:
        ordering = ['-init_date_at_dest']


class Photo(models.Model):
    url = models.CharField(max_length=500)
    destination = models.ForeignKey(Destination, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for destination_id: {self.destination_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm, ModelChoiceField, DateInput
from .models import Stop, Itinerary

class AddStopForm(ModelForm):
  class Meta:
    model = Stop
    # may need to revisit to add era/dest field
    fields = ['dest_description','init_date_at_dest', 'end_date_at_dest', 'comments']
    widgets = {
        'init_date_at_dest': DateInput(attrs={'type': 'date'}),
        'end_date_at_dest': DateInput(attrs={'type': 'date'}),
    }
    input_formats = [
        '%Y-%m-%d',  # Year-Month-Day (e.g., 2023-08-25)
        '%d/%m/%Y',  # Day/Month/Year (e.g., 25/08/2023)
            # Add more formats as needed
        ]
    
class ItinCreateForm(ModelForm):
    class Meta:
        model = Itinerary
        fields = ['init_name', 'itin_description', 'init_travel_date', 'end_travel_date', 'user_budget']
        widgets = {
            'init_travel_date': DateInput(attrs={'type': 'date'}),
            'end_travel_date': DateInput(attrs={'type': 'date'}),
        }
    input_formats = [
        '%Y-%m-%d',  # Year-Month-Day (e.g., 2023-08-25)
        '%d/%m/%Y',  # Day/Month/Year (e.g., 25/08/2023)
            # Add more formats as needed
        ]

main_app/views.py
# the following imports are for AWS, linked to the photo icebox feature
# import os
# import uuid
# import boto3
from django.shortcuts import get_object_or_404, render, redirect
# CBVs
from django.views.generic.edit import CreateView, UpdateView, DeleteView
# User
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

# Models
from .models import Destination, Itinerary, Stop, Era

# Import the mixin for class-based views
from django.contrib.auth.mixins import LoginRequiredMixin

# Import the login_required decorator
from django.contrib.auth.decorators import login_required

# Custom form imports
from .forms import AddStopForm, ItinCreateForm

# ------Home page view (Eras) (/home/)---------------
def home (request):
    eras = Era.objects.all().order_by('id')
    return render(request, 'home.html', {
       'eras': eras,
    })

# ------Itineraries (/itins/)-------------------------------------------
# Itineraries index
@login_required 
def itins_index(request):
  # Itins for logged in user
  itins = Itinerary.objects.filter(user=request.user).order_by('init_travel_date')
  return render(request, 'itins/index.html', {
    'itins': itins
  })


# Itinerary Details
@login_required 
def itins_detail(request, itin_id):
    itinerary = get_object_or_404(Itinerary, id=itin_id) 
    stops = itinerary.Itinerary_plan.all().order_by('init_date_at_dest')  # Retrieve all stops associated with this itinerary
    return render(request, 'itins/detail.html', {'itinerary': itinerary, 'stops': stops})


# Create Itinerary
class ItinCreate(LoginRequiredMixin, CreateView):
    model = Itinerary
    form_class = ItinCreateForm 
    # custom form overriding django one

  #overriding CBV properties to assign a user to a itinerary 
    def form_valid(self, form):
      # form.instance is the unsaved itin object / self.request.user is the logged in user object
      form.instance.user = self.request.user
      return super().form_valid(form)


# Update Itinerary
class ItinUpdate(LoginRequiredMixin, UpdateView):
    model = Itinerary
    form_class = ItinCreateForm 

    def form_valid(self, form):
        return super().form_valid(form)


# Delete Itinerary
class ItinDelete(LoginRequiredMixin, DeleteView):
  model = Itinerary
  success_url = '/itins'

# ------Stops (/itins/)----------------------------------------------- 
# Create/add one Stop associated the itinerary
@login_required
def add_stop(request, era_id, dest_id):
    destination = Destination.objects.get(id=dest_id,)
    itins = Itinerary.objects.filter(user=request.user)

    if request.method == 'POST':
        form = AddStopForm(request.POST)
        if form.is_valid():
            stop = form.save(commit=False)
            stop.destination = destination
            selected_itinerary_id = request.POST.get('itinerary')  # Get the selected itin ID
            selected_itinerary = Itinerary.objects.get(id=selected_itinerary_id)
            stop.itinerary = selected_itinerary  # Assign the selected destination to the stop
            stop.save()
            return redirect('dest_detail', era_id=era_id, dest_id=dest_id )
    else:
        form = AddStopForm()

    return render(request, 'itins/add_stop.html', {
       'form': form, 
       'destination_id': dest_id,
       'itins' : itins
         })


#Delete One Stop
@login_required
def delete_stop(request, itinerary_id, stop_id):
    itinerary = Itinerary.objects.get(id=itinerary_id)
    stop = Stop.objects.get(id=stop_id)

    if request.method == 'POST':
        stop.delete()
        return redirect('itins_detail', itin_id=itinerary_id)

    return render(request, 'itins/delete_stop.html', {'itinerary': itinerary, 'stop': stop})

#Edit One Stop
@login_required
def edit_stop(request, itinerary_id, stop_id):
    itinerary = Itinerary.objects.get(id=itinerary_id)
    stop = Stop.objects.get(id=stop_id)

    if request.method == 'POST':
        form = AddStopForm(request.POST, instance=stop)
        if form.is_valid():
            form.save()
            return redirect('itins_detail', itin_id=itinerary_id)
    else:
        form = AddStopForm(instance=stop)

    return render(request, 'itins/edit_stop.html', {'form': form, 'itinerary': itinerary, 'stop': stop})



#---------User------------------------------------------------------------------
# Using Joel's updated way so that the username is prefilled in if error
def signup(request):
  error_message = ''
  form = UserCreationForm(request.POST)
  if request.method == 'POST':
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('itins_index')
    else:
      error_message = 'Invalid sign up - try again'
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)


# --------Destination (/dests/)------------------------------------------ 
# Destinations Index
def destinations_index(request, era_id):
  era = Era.objects.get(id=era_id)
  return render(request, 'destinations/index.html', {
    'era': era,
  })

def destinations_detail(request, era_id, dest_id):
  era = Era.objects.get(id=era_id)
  destination = Destination.objects.get(id=dest_id)

  return render(request, 'destinations/detail.html', {
    'era': era, 
    'destination': destination,
  })

# --------Add photo function  - Wish list icebox(/dests/)---------------- 

# @login_required
# def add_photo(request, destination_id):
#   # photo-file maps to the "name" attr on the <input>
#   photo_file = request.FILES.get('photo-file', None)
#   if photo_file:
#     s3 = boto3.client('s3')
#     # Need a unique "key" (filename)
#     # It needs to keep the same file extension
#     # of the file that was uploaded (.png, .jpeg, etc.)
#     key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
#     try:
#       bucket = os.environ['S3_BUCKET']
#       s3.upload_fileobj(photo_file, bucket, key)
#       url = f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
#       Photo.objects.create(url=url, destination_id=destination_id)
#     except Exception as e:
#       print('An error occurred uploading file to S3')
#       print(e)
#   return redirect('dest_detail', destination_id=destination_id)

main_app/templates/destinations/detail.html
{% extends 'base.html' %}
{% block content %}

<section class="container">
    <div class="destination-detail">
        <div class="row padder"></div>
        <div class="row text-center">
            <h1 class="title">{{ destination.dest_name }}</h1>
        </div>
        <div class="row">
            <div class="col">
                <!-- carousel to hold multiple images for destination -->
                <div id="carouselExample" class="carousel slide">
                    <div class="carousel-inner gallery">
                        {% for photo in destination.photo_set.all %}
                            <div class="carousel-item">
                                <img src="{{photo.url}}" class="d-block screen w-100" alt="...">
                            </div>
                        {% empty %}
                            <div class="text-center">No Photos Uploaded</div>
                        {% endfor %}
                    </div>
                    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
                      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                      <span class="visually-hidden">Previous</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
                      <span class="carousel-control-next-icon" aria-hidden="true"></span>
                      <span class="visually-hidden">Next</span>
                    </button>
                </div>
            </div>
        </div>
    <!-- script to find first image and apply active class so the carousel works -->
        <script>
            document.querySelector('.gallery .carousel-item').classList.add('active')
        </script>
 
        <div class="padder"></div>
        <!-- version for no map -->
        <div class="row">
            <div class="col text-center">
                <h3 class="sub-title">{{ destination.dest_country }}</h3>
                <h4>Address: {{ destination.dest_address }}</h4>
            </div>
            <div class="col text-center">
                <h4 class="sub-title">Price Range: {{ destination.price_range }}</h4>
                <a href="{% url 'add_stop' era.id destination.id %}">
                    <button class="btn">ADD TO ITINERARY</button>
                </a>
            </div>
        </div>
        <div class="row mt-3">
            <p class="sub-title destination-card">{{ destination.dest_description }}</p>
        </div>
                
            <!-- version for iframe map  -->
            <!-- <div class="row">
                <div class="col placeholder">
                    <h1 class="">MAP GOES HERE</h1>
                </div>
                <div class="col text-center">
                    <h3 class="sub-title">{{ destination.dest_country }}</h3>
                    <h4 class="sub-title">Address: {{ destination.dest_address }}</h4>
                    <a href="{% url 'add_stop' era.id destination.id %}">
                        <button class="btn">Add to Itinerary</button>
                    </a>
                    <p class="sub-title destination-card">{{ destination.dest_description }}</p>
                </div>
            </div> -->
        
    </div>
    <div class="padder"></div>
    
</section>


{% endblock %}

main_app/templates/destinations/index.html
{% extends 'base.html' %}
{% block content %}

<section class="container">
    <h1 class="text-center title">Explore Destinations from {{ era.era_name }}</h1>
    <div class="row era-desc">
        <p> {{ era.era_description }} </p>
    </div>
    
    {% for destination in era.destinations.all %}
        <div class="destination-card">
            <div class="row bottom-row">
                <div class="col-4">
                    {% if destination.photo_set.first %}
                        <img class="img-fluid list-img" src="{{ destination.photo_set.first.url }}">
                    {% else %}
                        <p>No Image Found</p>
                    {% endif %}
                </div>
                <div class="col-8 row">
                    <a href="{% url 'dest_detail' era.id destination.id %}"><h2>{{ destination.dest_name }}</h2></a>
                    <h3>{{ destination.dest_country }}</h3>
                    <p class="truncate">{{ destination.dest_description }}</p>
                    <a href="{% url 'dest_detail' era.id destination.id %}">
                        <button class="btn">DETAIL</button>
                    </a>
                </div>
            </div>
        </div>
    {% endfor %}

</section>

{% endblock %}